services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: smithery-2api-app
    restart: unless-stopped
    ports:
      - "${APP_PORT:-8000}:8000"
    env_file:
      - .env
